services:
  gam-docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: patrickhaley/gam-docker:latest
    container_name: gam-docker
    volumes:
      - ./GAMConfig:/home/gam/GAMConfig
      - ./GAMWork:/home/gam/GAMWork
    environment:
      - PATH=/home/gam/bin:$PATH
      - GAMCFGDIR=/home/gam/GAMConfig
    entrypoint: /docker-entrypoint.sh
    command: tail -f /dev/null
    tty: true
    stdin_open: true